from functools import partial
from langchain_anthropic import ChatAnthropic
# from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, StateGraph, START
from IPython.display import Image, display
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate, MessagesPlaceholder
from langchain.prompts.chat import SystemMessagePromptTemplate
from langchain_core.messages import AIMessage, HumanMessage
from src.graph.solver import Solver
from src.graph.schemas import State
from src.graph.retrieval import retrieve_examples
from src.vector_store.vector_store_manager import VectorStoreManager
from langchain_community.embeddings import OpenAIEmbeddings


class WorkflowManager:

    def __init__(self):
        self.llm = ChatAnthropic(model="claude-3-7-sonnet-20250219", temperature=0)
        self.embeddings = OpenAIEmbeddings()  # You might need to adjust this based on your setup
        self.vector_store_manager = VectorStoreManager(embedding_model=self.embeddings)
        # Set up the retriever with empty documents for now
        # In a real scenario, you would load actual documents
        self.retriever = self.vector_store_manager.setup_hybrid_retriever(documents=[])
        
    def control_edge(self, state: State):
        if state.get("status") == "success":
            return END
        return "solve"
    
    def human_node(self, state: State) -> State:
        """
        Process human input and update the state accordingly.
        This node allows for human interaction within the workflow.
        
        Args:
            state: The current state of the workflow
            
        Returns:
            Updated state with human input incorporated
        """
        # If there's no messages in the state yet, initialize with empty list
        if "messages" not in state:
            state["messages"] = []
            
        # If there's human input in the state, add it to messages
        if "human_input" in state:
            state["messages"].append(HumanMessage(content=state["human_input"]))
            # Remove the human_input from state after processing
            del state["human_input"]
            
        return state
    
    @staticmethod
    def display_workflow(graph):
        try:
            display(Image(graph.get_graph().draw_mermaid_png()))
        except Exception:
            pass

    def evaluate(self, state: State) -> State:
        """
        Evaluate the solution generated by the solver.
        Determines if the solution is successful or needs further refinement.
        
        Args:
            state: The current state of the workflow
            
        Returns:
            Updated state with evaluation results
        """
        # Get the candidate solution from the state
        candidate = state.get("candidate")
        
        if not candidate:
            state["status"] = "needs_revision"
            return state
        
        if isinstance(candidate, AIMessage):
            # TODO: SHALL WE CHECK SPECIFIC TOOL BEING CALLED?
            if candidate.tool_calls and len(candidate.tool_calls) > 0:
                state["status"] = "success"
            else:
                state["status"] = "needs_revision"
        elif isinstance(candidate, dict):
            # If candidate is a dictionary (from the solver), check for code
            if "codebase" in candidate and candidate.get("codebase", {}).get("code"):
                state["status"] = "success"
            else:
                state["status"] = "needs_revision"
        else:
            state["status"] = "needs_revision"
        
        return state
    
    @staticmethod
    def _load_solver_prompt():
        # prompt = hub.pull("wfh/usaco-draft-solver")
        system_message = SystemMessagePromptTemplate(prompt=PromptTemplate(
                                            input_variables=['examples'], 
                                            input_types={}, 
                                            partial_variables={}, 
                                            template='''You are a world-class competitive programmer.
        Please reply with a Python 3 solution to the problem below.
        First, reason through the problem and conceptualize a solution.
        Then write detailed pseudocode to uncover any potential logical errors or omissions.
        Finally output the working Python code for your solution, ensuring to fix any errors uncovered while writing pseudocode.

        IMPORTANT: Even for database schema questions, provide a Python solution using SQLAlchemy, Django ORM, or similar libraries. DO NOT provide raw SQL - your code MUST include Python functions or classes with "def", "class", "import", or "from" statements.

        No outside libraries are allowed except standard Python libraries and SQLAlchemy/Django ORM for database questions.{examples}

        IMPORTANT: Your response MUST be formatted as a valid JSON object with the following structure:
        {{
        "codebase": {{
            "reasoning": "Your high-level conceptual solution",
            "pseudocode": "Your step-by-step outline of the approach in plain English",
            "code": "Your valid Python 3 solution to the problem (must include def, class, import, or from statements)",
            "tests": "Test cases or demonstration code to verify correctness (REQUIRED, even if minimal)"
        }},
        "report": {{
            "data_preprocessing": "Optional description of how data is loaded, cleaned, or featurized",
            "model_or_algorithm": "Optional description of which model or algorithm was chosen and why",
            "hyperparameters": "Optional description of key hyperparameters or tuning approach",
            "evaluation_metrics": "Optional description of which metrics or methods used for model evaluation",
            "assumptions_or_caveats": "Optional description of any domain-specific assumptions or known limitations"
        }}
        }}

        The report field is REQUIRED, even if some of its subfields are empty.
        Do not include any text outside of this JSON structure. Ensure all JSON keys and values are properly quoted.
        '''
        ))
        return ChatPromptTemplate.from_messages([
            system_message,
            MessagesPlaceholder(variable_name="messages")
        ])

    def create_workflow(self) -> StateGraph:
        workflow = StateGraph(state_schema=State)
        prompt = self._load_solver_prompt()
        draft_solver = Solver(self.llm, prompt.partial(examples=""))
        solver = Solver(self.llm, prompt)
        retrieve_with_retriever = partial(retrieve_examples, retriever=self.retriever)

        workflow.add_node("draft", draft_solver)
        workflow.add_edge(START, "draft")
        workflow.add_node("retrieve", retrieve_with_retriever)
        workflow.add_node("solve", solver)
        workflow.add_node("evaluate", self.evaluate)
        workflow.add_node("human", self.human_node)
        # Add connectivity
        workflow.add_edge("draft", "retrieve")
        workflow.add_edge("retrieve", "solve")
        workflow.add_edge("solve", "evaluate")
        workflow.add_edge("human", "solve")
        workflow.add_conditional_edges("evaluate", self.control_edge, 
                                       {END: END, "solve": "solve"})
        return workflow

    def return_graph(self, show_workflow: bool=False):
        # Compile the graph without a custom checkpointer for compatibility with langraph studio
        workflow = self.create_workflow()
        graph = workflow.compile()
        if show_workflow:
            self.display_workflow(graph=graph)
        return graph
