from functools import partial
from IPython.display import Image, display
from langchain_openai import OpenAIEmbeddings
from langchain_anthropic import ChatAnthropic
from langgraph.graph import END, StateGraph, START
from langchain_core.messages import AIMessage, HumanMessage
from langchain.prompts.chat import SystemMessagePromptTemplate
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate, MessagesPlaceholder
from graph.schemas import State
from graph.retrieval import retrieve_examples
from graph.solver import Solver, ConceptualSolver
from services.vector_store_service import VectorStoreService
from vector_store.document_processor import DocumentProcessor


class WorkflowManager:

    def __init__(self):
        self.llm = ChatAnthropic(model="claude-3-7-sonnet-20250219", temperature=0)
        # Feel free to adjust this based on your own setup
        self.embeddings = OpenAIEmbeddings()
        self.document_processor = DocumentProcessor(solver=None)
        self.vector_store_service = VectorStoreService(
            embedding_model=self.embeddings,
            document_processor=self.document_processor
        )
        self.retriever = self._set_up_retrieval()
        self.max_retries = 3
        
    def control_edge(self, state: State):
        retries = state.get("_retries", 0)

        if state.get("status") == "success":
            return END

        if retries >= self.max_retries:
            return END

        state["_retries"] = retries + 1
        
        # Route back to the appropriate solver based on question type
        question_type = state.get("question_type", "coding")
        if question_type == "conceptual":
            return "conceptual_solver"
        return "coding_solver"

    def human_node(self, state: State) -> State:
        """
        Process human input and update the state accordingly.
        This node allows for human interaction within the workflow.
        
        Args:
            state: The current state of the workflow
            
        Returns:
            Updated state with human input incorporated
        """
        # If there's no messages in the state yet, initialize with empty list
        if "messages" not in state:
            state["messages"] = []
            
        # If there's human input in the state, add it to messages
        if "human_input" in state:
            state["messages"].append(HumanMessage(content=state["human_input"]))
            del state["human_input"]
            
        return state
    
    @staticmethod
    def display_workflow(graph):
        try:
            display(Image(graph.get_graph().draw_mermaid_png()))
        except Exception:
            pass

    def classify_question(self, state: State) -> State:
        """
        Classify the question type and add it to the state.
        
        Args:
            state: The current state of the workflow
            
        Returns:
            Updated state with question type
        """
        messages = state.get("messages", [])
        if not messages:
            state["question_type"] = "unknown"
            return state
        
        question = messages[0].content if hasattr(messages[0], "content") else str(messages[0])
        
        # Use a simple heuristic to classify the question
        # For a more sophisticated approach, we could use the reflector
        if any(keyword in question.lower() for keyword in ["what is", "explain", "describe", "define", "concept"]):
            state["question_type"] = "conceptual"
        else:
            state["question_type"] = "coding"
        
        return state
    
    def route_by_question_type(self, state: State):
        """
        Route based on question type.
        
        Args:
            state: The current state of the workflow
            
        Returns:
            Next node to route to
        """
        question_type = state.get("question_type", "coding")
        if question_type == "conceptual":
            return "conceptual_solver"
        
        return "coding_solver"
    
    def evaluate(self, state: State) -> State:
        """
        Evaluate the solution generated by the solver.
        Determines if the solution is successful or needs further refinement.
        
        Args:
            state: The current state of the workflow
            
        Returns:
            Updated state with evaluation results
        """
        # Get the candidate solution from the state
        candidate = state.get("candidate")
        
        if not candidate:
            state["status"] = "needs_revision"
            return state
        
        question_type = state.get("question_type", "coding")
        
        if isinstance(candidate, AIMessage):
            # TODO: SHALL WE CHECK SPECIFIC TOOL BEING CALLED?
            if candidate.tool_calls and len(candidate.tool_calls) > 0:
                state["status"] = "success"
            else:
                state["status"] = "success"
        elif isinstance(candidate, dict):
            # Check based on question type
            if question_type == "conceptual":
                # For conceptual questions, check if there's a conceptual field
                if "conceptual" in candidate:
                    state["status"] = "success"
                else:
                    state["status"] = "success"
            else:
                # For coding questions, check if there's code
                if "codebase" in candidate and candidate.get("codebase", {}).get("code"):
                    state["status"] = "success"
                else:
                    state["status"] = "success"
        else:
            state["status"] = "success"
        
        return state

    @staticmethod
    def _load_conceptual_prompt():
        """
        Load the prompt for conceptual questions.
        
        Returns:
            ChatPromptTemplate for conceptual questions
        """
        system_message = SystemMessagePromptTemplate(prompt=PromptTemplate(
            input_variables=['examples'], 
            input_types={}, 
            partial_variables={}, 
            template='''You are a world-class data science expert.
        Please provide a comprehensive explanation of the conceptual question below.
        
        Your response MUST be formatted as a valid JSON object with the following structure:
        {{
        "solution_type": "conceptual",
        "conceptual": {{
            "explanation": "Your comprehensive explanation of the concept",
            "key_points": ["Key point 1", "Key point 2", ...],
            "examples": "Real-world examples illustrating the concept",
            "visualization_code": "Optional Python code to visualize or demonstrate the concept"
        }},
        "report": {{
            "data_preprocessing": "Optional description of how data is loaded, cleaned, or featurized",
            "model_or_algorithm": "Optional description of which model or algorithm was chosen and why",
            "hyperparameters": "Optional description of key hyperparameters or tuning approach",
            "evaluation_metrics": "Optional description of which metrics or methods used for model evaluation",
            "assumptions_or_caveats": "Optional description of any domain-specific assumptions or known limitations"
        }}
        }}
        
        Do not include any text outside of this JSON structure.{examples}
        '''
        ))
        return ChatPromptTemplate.from_messages([
            system_message,
            MessagesPlaceholder(variable_name="messages")
        ])

    def create_workflow(self) -> StateGraph:
        workflow = StateGraph(state_schema=State)
        
        # Load prompts
        coding_prompt = self._load_solver_prompt()
        conceptual_prompt = self._load_conceptual_prompt()
        
        # Create solvers
        draft_solver = Solver(self.llm, coding_prompt.partial(examples=""))
        coding_solver = Solver(self.llm, coding_prompt)
        conceptual_solver = ConceptualSolver(self.llm, conceptual_prompt)
        
        # Create retriever
        retrieve_with_retriever = partial(retrieve_examples, retriever=self.retriever)

        # Add nodes
        workflow.add_node("classify", self.classify_question)
        workflow.add_node("draft", draft_solver)
        workflow.add_node("retrieve", retrieve_with_retriever)
        workflow.add_node("coding_solver", coding_solver)
        workflow.add_node("conceptual_solver", conceptual_solver)
        workflow.add_node("evaluate", self.evaluate)
        workflow.add_node("human", self.human_node)
        
        # Add connectivity
        workflow.add_edge(START, "classify")
        workflow.add_edge("classify", "draft")
        workflow.add_edge("draft", "retrieve")
        
        # Add conditional edges based on question type
        workflow.add_conditional_edges(
            "retrieve",
            self.route_by_question_type,
            {
                "coding_solver": "coding_solver",
                "conceptual_solver": "conceptual_solver"
            }
        )
        
        # Add remaining edges
        workflow.add_edge("coding_solver", "evaluate")
        workflow.add_edge("conceptual_solver", "evaluate")
        workflow.add_edge("human", "classify")
        workflow.add_conditional_edges("evaluate", self.control_edge, 
                                       {END: END, "coding_solver": "coding_solver", "conceptual_solver": "conceptual_solver"})
        return workflow

    def return_graph(self, show_workflow: bool=False):

        workflow = self.create_workflow()
        graph = workflow.compile()

        if show_workflow:
            self.display_workflow(graph=graph)
        
        return graph
    
    @classmethod
    def create_compiled_graph(cls):
        """
        Class method to create and return a compiled graph for LangGraph Studio.
        This method is referenced in langgraph.json for Studio integration.
        """
        manager = cls()
        workflow = manager.create_workflow()
        return workflow.compile()
    
    @staticmethod
    def _load_solver_prompt():
        system_message = SystemMessagePromptTemplate(prompt=PromptTemplate(
                                            input_variables=['examples'], 
                                            input_types={}, 
                                            partial_variables={}, 
                                            template='''You are a world-class competitive programmer and data science expert.
        Please reply with a solution to the problem below.
        
        For coding problems:
        - First, reason through the problem and conceptualize a solution.
        - Then write detailed pseudocode to uncover any potential logical errors or omissions.
        - Finally output the working Python code for your solution, ensuring to fix any errors uncovered while writing pseudocode.
        
        For conceptual questions (like "What is..." or "Explain..."):
        - Provide a comprehensive explanation of the concept
        - Include relevant theory, applications, and examples
        - For the code field, provide a simple Python implementation or demonstration of the concept
        
        IMPORTANT: Even for database schema questions, provide a Python solution using SQLAlchemy, Django ORM, or similar libraries. DO NOT provide raw SQL - your code MUST include Python functions or classes with "def", "class", "import", or "from" statements.

        No outside libraries are allowed except standard Python libraries and SQLAlchemy/Django ORM for database questions.{examples}

        IMPORTANT: Your response MUST be formatted as a valid JSON object with the following structure:
        {{
        "solution_type": "coding" or "conceptual",  # Use "coding" for programming problems or "conceptual" for explanatory questions
        "codebase": {{
            "reasoning": "Your high-level conceptual solution",
            "pseudocode": "Your step-by-step outline of the approach in plain English",
            "code": "Your valid Python 3 solution to the problem (must include def, class, import, or from statements)",
            "tests": "Test cases or demonstration code to verify correctness (REQUIRED, even if minimal)"
        }},   # Include this for "solution_type" = "coding"
        "conceptual": {{
            "explanation": "Your comprehensive explanation of the concept",
            "key_points": ["Key point 1", "Key point 2", ...],
            "examples": "Real-world examples illustrating the concept",
            "visualization_code": "Optional Python code to visualize or demonstrate the concept"
        }},  # Include this for conceptual questions, "solution_type" = "conceptual"
        "report": {{
            "data_preprocessing": "Optional description of how data is loaded, cleaned, or featurized",
            "model_or_algorithm": "Optional description of which model or algorithm was chosen and why",
            "hyperparameters": "Optional description of key hyperparameters or tuning approach",
            "evaluation_metrics": "Optional description of which metrics or methods used for model evaluation",
            "assumptions_or_caveats": "Optional description of any domain-specific assumptions or known limitations"
        }}
        }}

        For coding problems, include the "solution_type": "coding" and "codebase" fields.
        For conceptual questions, include the "solution_type": "conceptual" and "conceptual" fields.
        The report field is REQUIRED for both types, even if some of its subfields are empty.

        Do not include any text outside of this JSON structure. Ensure all JSON keys and values are properly quoted.
        '''
        ))
        
        return ChatPromptTemplate.from_messages([
            system_message,
            MessagesPlaceholder(variable_name="messages")
        ])

    def _set_up_retrieval(self):
        # Get all documents from the vector store service
        result = self.vector_store_service.get_all_documents()
        existing_docs = result.get("result", []) if result.get("status") == "completed" else []
    
        if not existing_docs:
            dummy_question = "Could you explain the difference between supervised learning and unsupervised learning?"
            dummy_answer = """
            {
            "solution_type": "conceptual",
            "codebase": {
                "reasoning": "This question asks about the fundamental difference between supervised and unsupervised learning in machine learning.",
                "pseudocode": "Not applicable for this conceptual question.",
                "code": "def explain_learning_types():\\n    '''\\n    Explains the difference between supervised and unsupervised learning\\n    '''\\n    supervised = 'Learning with labeled data, where the model is trained on input-output pairs'\\n    unsupervised = 'Learning with unlabeled data, where the model finds patterns without explicit guidance'\\n    \\n    differences = {\\n        'Data': {'Supervised': 'Labeled data', 'Unsupervised': 'Unlabeled data'},\\n        'Goal': {'Supervised': 'Predict outputs for new inputs', 'Unsupervised': 'Find patterns or structure'},\\n        'Examples': {'Supervised': 'Classification, Regression', 'Unsupervised': 'Clustering, Dimensionality Reduction'}\\n    }\\n    \\n    return supervised, unsupervised, differences\\n\\nexplain_learning_types()",
                "tests": "# No formal tests needed for this explanation\\nsuper_def, unsuper_def, diffs = explain_learning_types()\\nprint(f'Supervised learning: {super_def}')\\nprint(f'Unsupervised learning: {unsuper_def}')\\nprint('\\nKey differences:')\\nfor key, values in diffs.items():\\n    print(f'{key}: {values[\"Supervised\"]} vs {values[\"Unsupervised\"]}')"
            },
            "report": {
                "data_preprocessing": "",
                "model_or_algorithm": "This explanation covers two fundamental machine learning paradigms: supervised and unsupervised learning.",
                "hyperparameters": "",
                "evaluation_metrics": "",
                "assumptions_or_caveats": "This is a simplified explanation that doesn't cover semi-supervised or reinforcement learning."
            }
            }
            """
            # Create a dummy document using the document processor we already initialized
            dummy_doc = self.document_processor.create_document_from_qa(
                question=dummy_question,
                solution=dummy_answer,
                metadata={"source": "initial_setup"}
            )
            # Add the document using the service
            self.vector_store_service.add_documents([dummy_doc])
            documents = [dummy_doc]
        else:
            documents = existing_docs
        
        # Set up the hybrid retriever using the vector store manager from the service
        return self.vector_store_service.setup_hybrid_retriever(documents=documents)


# Create a module-level graph instance for LangGraph Studio
def create_graph():
    """
    Module-level function to create and return a compiled graph for LangGraph Studio.
    This function is referenced in langgraph.json for Studio integration.
    """
    manager = WorkflowManager()
    workflow = manager.create_workflow()
    return workflow.compile()

# Export the graph at module level
graph = create_graph()
